name: CI validation
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    
jobs:
  linting:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        action: actions/checkout@v7
      - name: Lint Code
        action: astral-sh/ruff-action@v4.1.0
        with:
          src: ./src