name: CI validation

on:
  pull_request:
    branches:
      - main
jobs:
  ci:
    uses: Nivedit84/actions-1/.github/workflows/ci.yaml
    with:
      python-version: "3.14"
      source-directory: "src"