name: CI validation
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  linting:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
      - name: Lint Code
        uses: astral-sh/ruff-action@v4.1.0
        continue-on-error: true
        with:
          src: ./src
  secret_scanning:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN  }}